name: Delete Pheonix Deployment
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
    paths-ignore:
      - '.github/workflows/**'
      - '**.md'

env:
  PR_REPO_NAME: pr-${{ github.event.pull_request.node_id }}

jobs:
  delete-page-host:
    runs-on: ubuntu-latest
    steps:
      - name: Delete repository for temporary deployment
        uses: enigmaglass-docs/delete-repository-action@v1
        with:
          name: enigmaglass-docs/${{ env.PR_REPO_NAME }}
          access-token: ${{ secrets.PAT }}